# Generated by Django 5.0.3 on 2025-09-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
