# Generated by Django 5.0.3 on 2025-09-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hr'),
        ),
    ]
