# Generated by Django 5.0.3 on 2025-09-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_application_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
