# Generated by Django 5.0.3 on 2025-09-19 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='eligibility_cgpa',
        ),
        migrations.RemoveField(
            model_name='job',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='job',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='home.hr'),
        ),
    ]
