# Generated by Django 6.0.2 on 2026-03-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
