# Generated by Django 6.0.2 on 2026-03-10 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_studentprofile_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('In Review', 'In Review'), ('Shortlisted', 'Shortlisted'), ('Selected', 'Selected'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
        migrations.CreateModel(
            name='BookmarkedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='home.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='home.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'job')},
            },
        ),
    ]
